<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <UserSecretsId>79aea8ed-a1ec-4e36-b67d-07c85f782f29</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observa.Web\Observa.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sql\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
